version: "3.8"
services:
  mongodb:
    image: "mongo"
    hostname: "mongodb"
    ports:
      - "27017:27017"
  app-cont:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
